# Đặt tên hiển thị cho bàn phím (tránh lỗi hiện chữ N/A khiến OS tưởng rác và ẩn đi)
CONFIG_ZMK_KEYBOARD_NAME="My Macropad"

# Tắt chế độ 2Mbps PHY và kéo công suất để máy tính/điện thoại dễ quét thấy hơn
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Tắt chế độ 2Mbps PHY để tương thích tuyệt đối với card Bluetooth của Windows và điện thoại
CONFIG_BT_CTLR_PHY_2M=n

# Kéo công suất phát sóng Bluetooth lên mức tối đa (+8dBm) để quét cho khỏe
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
